POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "emailAddress": "jan.kowalski@trainig.pl"
}

###

GET http://localhost:8080/api/users/1
Accept: application/json

###

GET http://localhost:8080/api/users?lastNameFragment=Kow
Accept: application/json

###

POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Microservices in practice (e-book)",
  "description": "Book",
  "price": "100.99 PLN",
  "type": "EBOOK"
}

###

POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "products": [
    {
      "id": 1
    }
  ]
}

###

GET http://localhost:8080/api/products
Accept: application/json

###

POST http://localhost:8080/api/products/1/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pom.xml"

< ./pom.xml
--WebAppBoundary--